
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGIN END FOOD HEAVY KG LIGHT LOAD NOME PESO_HEAVY PESO_LEVE ROUTE SAIL TO TOXIC UNLOAD WEIGHTs : ROUTE NOME BEGIN fase_heavy ENDfase_heavy : LOAD HEAVY NOME WEIGHT PESO_HEAVY KG fase_heavy UNLOAD HEAVY fase_heavyfase_heavy : LOAD LIGHT NOME WEIGHT PESO_LEVE KG fase_light UNLOAD LIGHT fase_heavyfase_heavy : LOAD FOOD NOME WEIGHT PESO_LEVE KG fase_food UNLOAD FOOD fase_heavyfase_heavy : LOAD TOXIC NOME WEIGHT PESO_LEVE KG fase_toxic UNLOAD TOXIC fase_heavyfase_heavy : SAIL TO NOME fase_heavyfase_heavy : emptyfase_light : LOAD LIGHT NOME WEIGHT PESO_LEVE KG fase_light UNLOAD LIGHT fase_lightfase_light : LOAD FOOD NOME WEIGHT PESO_LEVE KG fase_food UNLOAD FOOD fase_lightfase_light : LOAD TOXIC NOME WEIGHT PESO_LEVE KG fase_toxic UNLOAD TOXIC fase_lightfase_light : SAIL TO NOME fase_lightfase_light : emptyfase_light : fase_foodfase_light : fase_toxicfase_food : SAIL TO NOME fase_foodfase_food : LOAD LIGHT NOME WEIGHT PESO_LEVE KG fase_food UNLOAD LIGHT fase_foodfase_food : LOAD FOOD NOME WEIGHT PESO_LEVE KG fase_food UNLOAD FOOD fase_foodfase_food : emptyfase_toxic : LOAD TOXIC NOME WEIGHT PESO_LEVE KG fase_toxic UNLOAD TOXIC fase_toxicfase_toxic : LOAD LIGHT NOME WEIGHT PESO_LEVE KG fase_toxic UNLOAD LIGHT fase_toxicfase_toxic : SAIL TO NOME fase_toxicfase_toxic : emptyempty :'
    
_lr_action_items = {'ROUTE':([0,],[2,]),'$end':([1,9,],[0,-1,]),'NOME':([2,10,11,12,13,14,49,50,51,53,54,55,57,58,59,61,141,142,],[3,15,16,17,18,19,63,64,65,67,68,69,71,72,73,75,143,144,]),'BEGIN':([3,],[4,]),'LOAD':([4,19,29,30,31,32,62,66,67,70,71,74,75,99,100,101,102,103,104,105,122,123,124,125,126,127,128,144,147,],[6,6,6,34,40,44,6,6,34,6,40,6,44,34,40,44,40,40,44,44,34,40,44,34,134,40,44,134,134,]),'SAIL':([4,19,29,30,31,32,62,66,67,70,71,74,75,99,100,101,102,103,104,105,122,123,124,125,126,127,128,144,147,],[7,7,7,38,42,46,7,7,38,7,42,7,46,38,42,46,42,42,46,46,38,42,46,38,137,42,46,137,137,]),'END':([4,5,8,19,24,62,66,70,74,76,80,86,90,],[-23,9,-7,-23,-6,-23,-23,-23,-23,-2,-3,-4,-5,]),'HEAVY':([6,48,],[10,62,]),'LIGHT':([6,34,40,44,52,115,116,117,134,],[11,49,54,59,66,122,123,124,141,]),'FOOD':([6,34,40,56,118,120,134,],[12,50,55,70,125,127,50,]),'TOXIC':([6,34,44,60,119,121,134,],[13,51,58,74,126,128,51,]),'TO':([7,38,42,46,137,],[14,53,57,61,142,]),'UNLOAD':([8,19,24,29,30,31,32,33,35,36,37,39,41,43,45,47,62,66,67,70,71,74,75,76,80,81,82,83,86,87,90,91,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,122,123,124,125,126,127,128,129,130,131,132,133,135,136,138,139,140,144,147,],[-7,-23,-6,-23,-23,-23,-23,48,52,-13,-14,-12,56,-18,60,-22,-23,-23,-23,-23,-23,-23,-23,-2,-3,-11,-13,-14,-4,-15,-5,-21,-23,-23,-23,-23,-23,-23,-23,115,116,117,118,119,116,120,121,117,-23,-23,-23,-23,-23,-23,-23,-8,-16,-20,-13,-9,-14,-10,-12,-17,-19,-23,-23,]),'WEIGHT':([15,16,17,18,63,64,65,68,69,72,73,143,],[20,21,22,23,77,78,79,84,85,88,89,145,]),'PESO_HEAVY':([20,],[25,]),'PESO_LEVE':([21,22,23,77,78,79,84,85,88,89,145,],[26,27,28,92,93,94,95,96,97,98,146,]),'KG':([25,26,27,28,92,93,94,95,96,97,98,146,],[29,30,31,32,99,100,101,102,103,104,105,147,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'s':([0,],[1,]),'fase_heavy':([4,19,29,62,66,70,74,],[5,24,33,76,80,86,90,]),'empty':([4,19,29,30,31,32,62,66,67,70,71,74,75,99,100,101,102,103,104,105,122,123,124,125,126,127,128,144,147,],[8,8,8,39,43,47,8,8,39,8,43,8,47,39,43,47,43,43,47,47,39,43,47,39,138,43,47,138,138,]),'fase_light':([30,67,99,122,125,126,144,147,],[35,81,106,129,133,136,81,106,]),'fase_food':([30,31,67,71,99,100,102,103,122,123,125,126,127,144,147,],[36,41,82,87,107,109,111,112,36,130,132,36,139,82,107,]),'fase_toxic':([30,32,67,75,99,101,104,105,122,124,125,126,128,144,147,],[37,45,83,91,108,110,113,114,37,131,37,135,140,83,108,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> s","S'",1,None,None,None),
  ('s -> ROUTE NOME BEGIN fase_heavy END','s',5,'p_S','analisador.py',43),
  ('fase_heavy -> LOAD HEAVY NOME WEIGHT PESO_HEAVY KG fase_heavy UNLOAD HEAVY fase_heavy','fase_heavy',10,'p_fase_heavy_load_heavy','analisador.py',48),
  ('fase_heavy -> LOAD LIGHT NOME WEIGHT PESO_LEVE KG fase_light UNLOAD LIGHT fase_heavy','fase_heavy',10,'p_fase_heavy_load_light','analisador.py',54),
  ('fase_heavy -> LOAD FOOD NOME WEIGHT PESO_LEVE KG fase_food UNLOAD FOOD fase_heavy','fase_heavy',10,'p_fase_heavy_load_food','analisador.py',60),
  ('fase_heavy -> LOAD TOXIC NOME WEIGHT PESO_LEVE KG fase_toxic UNLOAD TOXIC fase_heavy','fase_heavy',10,'p_fase_heavy_load_toxic','analisador.py',66),
  ('fase_heavy -> SAIL TO NOME fase_heavy','fase_heavy',4,'p_fase_heavy_sail','analisador.py',72),
  ('fase_heavy -> empty','fase_heavy',1,'p_fase_heavy_empty','analisador.py',76),
  ('fase_light -> LOAD LIGHT NOME WEIGHT PESO_LEVE KG fase_light UNLOAD LIGHT fase_light','fase_light',10,'p_fase_light_load_light','analisador.py',81),
  ('fase_light -> LOAD FOOD NOME WEIGHT PESO_LEVE KG fase_food UNLOAD FOOD fase_light','fase_light',10,'p_fase_light_load_food','analisador.py',87),
  ('fase_light -> LOAD TOXIC NOME WEIGHT PESO_LEVE KG fase_toxic UNLOAD TOXIC fase_light','fase_light',10,'p_fase_light_load_toxic','analisador.py',93),
  ('fase_light -> SAIL TO NOME fase_light','fase_light',4,'p_fase_light_sail','analisador.py',99),
  ('fase_light -> empty','fase_light',1,'p_fase_light_empty','analisador.py',103),
  ('fase_light -> fase_food','fase_light',1,'p_fase_light_food','analisador.py',107),
  ('fase_light -> fase_toxic','fase_light',1,'p_fase_light_toxic','analisador.py',111),
  ('fase_food -> SAIL TO NOME fase_food','fase_food',4,'p_fase_food_sail','analisador.py',117),
  ('fase_food -> LOAD LIGHT NOME WEIGHT PESO_LEVE KG fase_food UNLOAD LIGHT fase_food','fase_food',10,'p_fase_food_load_light','analisador.py',121),
  ('fase_food -> LOAD FOOD NOME WEIGHT PESO_LEVE KG fase_food UNLOAD FOOD fase_food','fase_food',10,'p_fase_food_load_food','analisador.py',127),
  ('fase_food -> empty','fase_food',1,'p_fase_food_empty','analisador.py',133),
  ('fase_toxic -> LOAD TOXIC NOME WEIGHT PESO_LEVE KG fase_toxic UNLOAD TOXIC fase_toxic','fase_toxic',10,'p_fase_toxic_load_toxic','analisador.py',139),
  ('fase_toxic -> LOAD LIGHT NOME WEIGHT PESO_LEVE KG fase_toxic UNLOAD LIGHT fase_toxic','fase_toxic',10,'p_fase_toxic_load_light','analisador.py',145),
  ('fase_toxic -> SAIL TO NOME fase_toxic','fase_toxic',4,'p_fase_toxic_sail','analisador.py',151),
  ('fase_toxic -> empty','fase_toxic',1,'p_fase_toxic_empty','analisador.py',155),
  ('empty -> <empty>','empty',0,'p_empty','analisador.py',160),
]
