
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGIN END HEAVY KG LIGHT LOAD NOME PESO_HEAVY PESO_LEVE ROUTE SAIL TO UNLOAD WEIGHTs : ROUTE NOME BEGIN fase_heavy ENDfase_heavy : LOAD HEAVY NOME WEIGHT PESO_HEAVY KG fase_heavy UNLOAD HEAVY fase_heavyfase_heavy : fase_lightfase_heavy : SAIL TO NOME fase_heavyfase_heavy : emptyfase_light : LOAD LIGHT NOME WEIGHT PESO_LEVE KG fase_light UNLOAD LIGHT fase_lightfase_light : SAIL TO NOME fase_lightfase_light : emptyempty :'
    
_lr_action_items = {'ROUTE':([0,],[2,]),'$end':([1,10,],[0,-1,]),'NOME':([2,11,12,13,32,],[3,14,15,16,35,]),'BEGIN':([3,],[4,]),'LOAD':([4,16,23,24,33,34,35,],[6,6,6,26,6,26,26,]),'SAIL':([4,16,23,24,33,34,35,],[8,8,8,28,8,28,28,]),'END':([4,5,7,9,16,19,20,29,33,34,35,36,37,38,],[-9,10,-3,-5,-9,-4,-3,-8,-9,-9,-9,-2,-6,-7,]),'HEAVY':([6,30,],[11,33,]),'LIGHT':([6,26,31,],[12,12,34,]),'UNLOAD':([7,9,16,19,20,23,24,25,27,29,33,34,35,36,37,38,],[-3,-5,-9,-4,-3,-9,-9,30,31,-8,-9,-9,-9,-2,-6,-7,]),'TO':([8,28,],[13,32,]),'WEIGHT':([14,15,],[17,18,]),'PESO_HEAVY':([17,],[21,]),'PESO_LEVE':([18,],[22,]),'KG':([21,22,],[23,24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'s':([0,],[1,]),'fase_heavy':([4,16,23,33,],[5,19,25,36,]),'fase_light':([4,16,23,24,33,34,35,],[7,20,7,27,7,37,38,]),'empty':([4,16,23,24,33,34,35,],[9,9,9,29,9,29,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> s","S'",1,None,None,None),
  ('s -> ROUTE NOME BEGIN fase_heavy END','s',5,'p_S','analisador.py',43),
  ('fase_heavy -> LOAD HEAVY NOME WEIGHT PESO_HEAVY KG fase_heavy UNLOAD HEAVY fase_heavy','fase_heavy',10,'p_fase_heavy_load','analisador.py',48),
  ('fase_heavy -> fase_light','fase_heavy',1,'p_fase_heavy_light','analisador.py',54),
  ('fase_heavy -> SAIL TO NOME fase_heavy','fase_heavy',4,'p_fase_heavy_sail','analisador.py',58),
  ('fase_heavy -> empty','fase_heavy',1,'p_fase_heavy_empty','analisador.py',62),
  ('fase_light -> LOAD LIGHT NOME WEIGHT PESO_LEVE KG fase_light UNLOAD LIGHT fase_light','fase_light',10,'p_fase_light_load','analisador.py',67),
  ('fase_light -> SAIL TO NOME fase_light','fase_light',4,'p_fase_light_sail','analisador.py',73),
  ('fase_light -> empty','fase_light',1,'p_fase_light_empty','analisador.py',77),
  ('empty -> <empty>','empty',0,'p_empty','analisador.py',82),
]
